Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end

  config.vm.define :haproxy do |haproxy|
    haproxy.vm.box = "fepe/stream8"
    haproxy.vm.network :private_network, ip: "192.168.50.2"
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.synced_folder ".", "/vagrant"
  end

  config.vm.define :sender do |sender|
    sender.vm.box = "fepe/stream8"
    sender.vm.network :private_network, ip: "192.168.50.3"
    sender.vm.hostname = "sender"
    sender.vm.synced_folder ".", "/vagrant"
  end

end
