# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :prometheus do |prometheus|
    prometheus.vm.box = "bento/ubuntu-22.04"
    prometheus.vm.network :private_network, ip: "192.168.50.4"
    prometheus.vm.hostname = "prometheus"
  end
  
  config.vm.define :grafana do |grafana|
    grafana.vm.box = "bento/ubuntu-22.04"
    grafana.vm.network :private_network, ip: "192.168.50.5"
    grafana.vm.hostname = "grafana"
  end
  
end
